### SignUp
POST http://localhost:3003/user/signup/
content-type: application/json


{
    "name": "john doe",
    "email": "johndoe@gmail.com",
    "password": "12345678",
    "bio": "I Am dev FullSctak",
    "banner_url": "",
    "avatar_url": ""
}
### Login
POST http://localhost:3003/user/login/
content-type: application/json


{
    "email": "johndoe@gmail.com",
    "password": "12345678"
}