### SignUp
POST http://localhost:3003/user/signup/
content-type: application/json


{
    "name": "john doe",
    "email": "jodoe@gmail.com",
    "password": "12345678",
    "bio": "I Am dev FullSctak",
    "banner_url": "",
    " website_url ": "",
    "localization": "",
    "birth_date" :  "2022-05-12T10:43:09.555Z",
    "avatar_url": ""
}
### Login
POST http://localhost:3003/user/login/
content-type: application/json


{
    "email": "johndoe@gmail.com",
    "password": "12345678"
}